server:
  port: 8082
spring:
  datasource:
    platform: postgres
    username: sa
    password: sa
    url: jdbc:postgresql://localhost:5432/markets
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: mqsa
    password: sa
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
