server:
  port: 8083
  gateway:
    host: http://localhost
    port: 8080

logging:
  file:
    name: /opt/cc/log/logging.log
  level:
    web: debug

spring:
  datasource:
    platform: postgres
    username: sa
    password: sa
    url: jdbc:postgresql://localhost:5432/logging
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: mqsa
    password: sa
