server:
  port: 8083

logging:
  level:
    web: trace
spring:
  liquibase:
    enabled: false
  application:
    name: '@name@'
  data:
    mongodb:
      authentication-database: admin
      username: sa
      password: sa
      database: logging
      port: 27017
      host: localhost
