logging:
  level:
    web: debug

spring:
  data:
    mongodb:
      authentication-database: admin
      username: sa
      password: sa
      database: logging
      port: 27017
      host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: mqsa
    password: sa
