server:
  port: 8083
spring:
  datasource:
    platform: postgres
    username: sa
    password: sa
    url: jdbc:postgresql://localhost:5432/event_log
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
