server:
  port: 0
spring:
  data:
    mongodb:
      authentication-database: admin
      username: sa
      password: sa
      database: logging
      port: 27017
      host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: mqsa
    password: sa
eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
