server:
  port: 8083

logging:
  level:
    web: trace
spring:
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  application:
    name: '@name@'
  datasource:
    platform: postgres
    username: sa
    password: sa
    url: jdbc:postgresql://localhost:5432/event_log
    driver-class-name: org.postgresql.Driver
