logging:
  level:
    web: trace

eureka:
  instance:
    hostname: service-a
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://registry-service:8761/eureka/
