server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: sa
    password: sa
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect